### ISSUE TITLE
atom-hg makes statusbar throw an error

### ISSUE THREAD

**Issue by ghost** [victor-torres/atom-hg#23] opened 2016-07-27 10:44 UTC
when enabling atom-hg on the 1.9.0 beta it produces the following error on save (and other actions).

**Atom Version**: 1.9.0-beta1
**System**: Ubuntu 16.04.1
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'ahead' of null

```
At /usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:213

TypeError: Cannot read property 'ahead' of null
    at status-bar-git.GitView.updateAheadBehindCount (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:213:78)
    at status-bar-git.GitView.update (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:171:12)
    at status-bar-git.GitView.subscribeToActiveItem (/usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:81:19)
    at /usr/share/atom-beta/resources/app.asar/node_modules/status-bar/lib/git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom-beta/resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom-beta/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:660:19)
```
### Commands

```
  2x -0:32.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.7.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -0:31.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:29.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:26.4.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:26.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.7.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:24.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:21.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:18.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "activate-power-mode",
      "ctags-status"
    ],
    "ignoredNames": [
      "*.pyc"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "~/projects",
    "themes": [
      "atom-material-ui",
      "github-2016-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aesthetic-ui, v2.0.0 (inactive)
atom-beautify, v0.29.10 (active)
atom-github-2014-syntax, v1.6.0 (inactive)
atom-hg, v2.0.4 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.3 (active)
ava, vundefined (active)
base16-ocean-dark-spacegray, v0.12.0 (inactive)
base16-ocean-dark-syntax-theme, v0.1.9 (inactive)
clipboard-plus, v0.5.1 (active)
color-picker, v2.2.2 (active)
ctags-status, v1.3.5 (inactive)
emmet, v2.4.3 (active)
file-icons, v1.7.17 (active)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
github-2016-syntax, v1.2.0 (active)
indent-guide-improved, v1.4.9 (active)
language-postcss, v1.2.3 (active)
language-restructuredtext, v1.0.0 (active)
linter, v1.11.14 (active)
linter-eslint, v7.2.4 (active)
linter-stylelint, v3.0.2 (active)
minimap, v4.24.7 (active)
minimap-pigments, v0.2.1 (active)
perfectionist, v1.0.1 (inactive)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (active)
pulsing-cursor, v0.3.1 (active)
source-preview, v0.5.0 (inactive)
source-preview-postcss, v0.1.4 (inactive)
spacegray-dark-syntax, v0.2.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
stylefmt, v2.1.0 (inactive)
svg-preview, v0.7.4 (active)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (active)
toggle-quotes, v1.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by rochford77** [comment] 2016-08-02 01:02
have this issue as well. removed atom from the machine and the .atom folder, reinstalled. atom worked great until i installed this package. with this package enabled, (or seemingly any mercurial related package) i get the following logs: (it should be noted, i also tried to reinstall Hg and deleted and re-synced my repo...)

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.0
**System**: Mac OS X 10.11.6
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'ahead' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213

TypeError: Cannot read property 'ahead' of null
    at status-bar-git.GitView.updateAheadBehindCount (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213:78)
    at status-bar-git.GitView.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:171:12)
    at status-bar-git.GitView.subscribeToActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:81:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:660:19)
```

### Commands

```
     -2:05.9.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-ruby",
      "linter-pylint",
      "linter-javac",
      "linter-htmlhint",
      "linter-csslint"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-hg, v2.0.4 (active)
file-icons, v1.7.17 (active)
linter, v1.11.14 (active)
linter-csslint, v1.3.2 (inactive)
linter-htmlhint, v1.3.0 (inactive)
linter-javac, v1.9.4 (inactive)
linter-jshint, v2.1.0 (active)
linter-pylint, v1.2.1 (inactive)
linter-ruby, v1.2.2 (inactive)
minimap, v4.24.7 (active)
monokai, v0.18.0 (active)
pigments, v0.31.2 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by rochford77** [comment] 2016-08-03 05:15
see here, related:

https://github.com/atom/status-bar/issues/161

**Comment by victor-torres** [comment] 2016-08-03 18:56
@rochford77 @stefan-kern https://github.com/atom/status-bar/issues/161#issuecomment-236837592

Looks like we’ll have to refactor the whole plugin approach, which was already discussed here: https://github.com/victor-torres/atom-hg/issues/15

Unfortunately I have no time for doing so. I’m currently working a lot and using PyCharm in a daily basis rather than Atom. So this means we need help here. If one of you guys could contribute to the project it would be awesome. 

Create some Pull Request and I’ll be glad to review it. 

BTW, Sorry.

**Comment by rochford77** [comment] 2016-08-03 22:39
@victor-torres, is there any way you could update the plugin/description with a warning for it not working if on atom > 1.8? This renders the editor unusable and could cause some real headaches trying to track down what plugin is causing it. IMHO, it's rather irresponsible to knowingly leave something out there that can bring the editor to its knees without a disclaimer of sorts. I know your busy but it might save some people quite a bit of time, especially when the warning says status-bar is failing, not atom-hg. 

Just a thought.... I'm not trying to be a jerk or anything, I understand that you are busy :-)

**Comment by victor-torres** [comment] 2016-08-04 13:26
@rochford77 I did it yesterday right after commenting here as you can see: https://github.com/victor-torres/atom-hg/commit/9acd953ba886c22da67a8065950a6226cd401689

And yeah, that’s not our fault status-bar and Atom’s API keeps changing. I really wish I was able to solve all these problems.

**Comment by victor-torres** [comment] 2016-08-04 13:40
(clicked close by mistake)

**Comment by v3ss0n** [comment] 2016-08-18 23:39
so atom-hg is basically abandoned now? 
How hard would it take for someone unfamilar with this to maintain?

**Comment by rochford77** [comment] 2016-08-18 23:42
Look in the pull requests. It looks like there is a fix submitted, waiting for @victor-torres to pull it and update. He said he uses jetbrains now though so it's not a priority for him.

**Comment by victor-torres** [comment] 2016-08-19 00:38
Merged pull request. I'll test it and then release a new version in a while.

**Comment by v3ss0n** [comment] 2016-08-19 00:41
i will test this in a min

**Comment by victor-torres** [comment] 2016-08-19 00:44
```
$ apm publish 2.0.7                                                                                                                                                                              [21:44:13]
Preparing and tagging a new version ✓
Pushing v2.0.7 tag ✓
Publishing atom-hg@v2.0.7 ✓
```

**Closed as completed by victor-torres** 2016-08-19 00:44 UTC

**Comment by victor-torres** [comment] 2016-08-19 00:46
Thank you guys for the support, specially for @mevatron (pull request) and @AndrewNelis (atom-svn fix).

**Comment by v3ss0n** [comment] 2016-08-19 00:50
@victor-torres  Tested! works fine , no error and display diffs!
Thanks a lot guys!!

**Comment by mevatron** [comment] 2016-08-19 02:23
@victor-torres Happy to help! I'll be updating from my locally hacked version shortly :)

**Comment by v3ss0n** [comment] 2016-08-19 17:56
thanks @mevatron  and AndrewNelis!
